--- #YAML:1.0
name:                Wx-Perl-Packager
version:             0.11
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    Wx:                            0.49
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mark Dootson <mdootson@cpan.org>
