--- #YAML:1.0
name:                Wx-Perl-Packager
version:             0.19
abstract:            ~
license:             ~
author:              
    - Mark Dootson <mdootson@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
    Class::Accessor:               0
    Digest::MD5:                   0
    Wx:                            0.49
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
